version: '3.8'

services:
  chrome-bot:
    build: .
    container_name: meet-bot
    volumes:
      - .:/app  # Mount entire project directory to container root
      - ./screenshots:/app/screenshots  # Dedicated screenshots folder
      - ./logs:/app/logs  # Dedicated logs folder  
      - ./output:/app/output  # Dedicated output folder
      - ./data:/app/data  # Additional data folder for any new files
    environment:
      - DISPLAY=:99
      - PYTHONPATH=/app
    shm_size: 2gb  # Increase shared memory for Chrome
    security_opt:
      - seccomp:unconfined  # Required for Chrome sandbox
    cap_add:
      - SYS_ADMIN  # Required for Chrome
    stdin_open: true
    tty: true
    restart: unless-stopped
