version: '3.8'

services:
  app:
    build: .
    image: app-base
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:11minhan@host.docker.internal:3306/sercuescribe?charset=utf8mb4
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    image: app-base
    environment:
      - DATABASE_URL=mysql+pymysql://root:11minhan@host.docker.internal:3306/sercuescribe?charset=utf8mb4
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - app
    command: celery -A app.core.celery worker --loglevel=info

  # db:
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=11minhan
  #     - MYSQL_DATABASE=sercuescribe
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=11minhan
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  flower:
    image: app-base
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - app
    command: celery -A app.core.celery flower --port=5555

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # adminer:
  #   image: adminer
  #   restart: always
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=db
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
      
volumes:
  minio_data:
  redis_data:
