"""Tạo revision mới tự động 2

Revision ID: 3d0556ab5839
Revises: 4b9a3e9f2313
Create Date: 2025-07-22 08:00:46.797918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d0556ab5839'
down_revision: Union[str, Sequence[str], None] = '4b9a3e9f2313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('bucket_name', sa.String(length=255), nullable=True))
    op.add_column('recordings', sa.Column('object_name', sa.String(length=255), nullable=True))
    op.alter_column('recordings', 'transcription',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'transcription',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('recordings', 'object_name')
    op.drop_column('recordings', 'bucket_name')
    # ### end Alembic commands ###
